const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Tween,
		C3.Plugins.Mouse,
		C3.Behaviors.Timer,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Arr,
		C3.Plugins.Keyboard,
		C3.Plugins.AJAX,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Arr.Acts.Insert,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying
	];
};
self.C3_JsPropNameTable = [
	{id: 0},
	{progress: 0},
	{MoveTo: 0},
	{Tween: 0},
	{Marble: 0},
	{Mouse: 0},
	{Timer: 0},
	{Player: 0},
	{currWpt: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{ArrMarbles: 0},
	{Keyboard: 0},
	{ArrInChain: 0},
	{ArrOffsets: 0},
	{AJAX: 0},
	{MarbleParticles: 0},
	{Background: 0},
	{Fader: 0},
	{TextTutorial: 0},
	{Icons: 0},
	{TextMarbles: 0},
	{TextLives: 0},
	{TextGameOver: 0},
	{MuzzleFlash: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{lastType: 0},
	{progressSpeed: 0},
	{canSpawn: 0},
	{tutorial: 0},
	{gameOver: 0},
	{lives: 0},
	{marblesDestroyed: 0},
	{STARTING_PROGRESS: 0},
	{MARBLE_SPEEDUP: 0},
	{MARBLE_SLOWDOWN: 0},
	{PLAYER_COOLDOWN: 0},
	{lastMarbleProgress: 0},
	{returnIdx: 0},
	{uid: 0},
	{inChain: 0},
	{frontmost: 0},
	{idx: 0},
	{marbleType: 0},
	{marbleUID: 0},
	{marbleIdx: 0},
	{UID: 0},
	{bulletType: 0}
];

self.InstanceType = {
	Marble: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Player: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	ArrMarbles: class extends self.IArrayInstance {},
	Keyboard: class extends self.IInstance {},
	ArrInChain: class extends self.IArrayInstance {},
	ArrOffsets: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	MarbleParticles: class extends self.IParticlesInstance {},
	Background: class extends self.ISpriteInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	TextTutorial: class extends self.ITextInstance {},
	Icons: class extends self.ISpriteInstance {},
	TextMarbles: class extends self.ITextInstance {},
	TextLives: class extends self.ITextInstance {},
	TextGameOver: class extends self.ITextInstance {},
	MuzzleFlash: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {}
}