const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Plugins.Timeline,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Timeline.Cnds.IsAnyPlaying,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Timeline.Acts.PlayTimelineByName,
		C3.Plugins.Timeline.Cnds.OnKeyframeReached,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Particles.Acts.SetPosToObject
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Text: 0},
	{TopdownCoffeeMug: 0},
	{TimelineController: 0},
	{Table: 0},
	{BagOfCoffee: 0},
	{MineralWater: 0},
	{Spacebar: 0},
	{BGSolid: 0},
	{Sine: 0},
	{Sine2: 0},
	{Grinder: 0},
	{CoffeeBeansParticles: 0},
	{GrinderCup: 0},
	{GroundCoffeeParticles: 0},
	{GrinderSpout: 0},
	{PortafilterLateral: 0},
	{Book: 0},
	{Tamper: 0},
	{EspressoMachine: 0},
	{BGSlide04: 0},
	{CoffeeCup: 0},
	{LiquidCoffeeParticles: 0},
	{EspressoMachineSpout: 0},
	{Pitcher: 0},
	{MilkParticles: 0},
	{TopdownEmptyMug: 0},
	{Sprite: 0},
	{Touch: 0},
	{currSlideAnim: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	TopdownCoffeeMug: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {},
	Table: class extends self.ISpriteInstance {},
	BagOfCoffee: class extends self.ISpriteInstance {},
	MineralWater: class extends self.ISpriteInstance {},
	Spacebar: class extends self.ISpriteInstance {},
	BGSolid: class extends self.ITiledBackgroundInstance {},
	Grinder: class extends self.ISpriteInstance {},
	CoffeeBeansParticles: class extends self.IParticlesInstance {},
	GrinderCup: class extends self.ISpriteInstance {},
	GroundCoffeeParticles: class extends self.IParticlesInstance {},
	GrinderSpout: class extends self.ISpriteInstance {},
	PortafilterLateral: class extends self.ISpriteInstance {},
	Book: class extends self.ISpriteInstance {},
	Tamper: class extends self.ISpriteInstance {},
	EspressoMachine: class extends self.ISpriteInstance {},
	BGSlide04: class extends self.ISpriteInstance {},
	CoffeeCup: class extends self.ISpriteInstance {},
	LiquidCoffeeParticles: class extends self.IParticlesInstance {},
	EspressoMachineSpout: class extends self.ISpriteInstance {},
	Pitcher: class extends self.ISpriteInstance {},
	MilkParticles: class extends self.IParticlesInstance {},
	TopdownEmptyMug: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {}
}