const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.BinaryData,
		C3.Plugins.Keyboard,
		C3.Plugins.Arr,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.gamepad,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.LocalStorage,
		C3.Plugins.Dictionary,
		C3.Plugins.Timeline,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Behaviors.Timer,
		C3.Plugins.Particles,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Plugins.Tilemap,
		C3.Behaviors.Flash,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.scrolly,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsDoubleJumpEnabled,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Platform.Acts.ResetDoubleJump,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Exps.Angle,
		C3.Behaviors.Platform.Exps.JumpStrength,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Exps.At,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Exps.TagAt,
		C3.Plugins.System.Acts.SetLayerEffectParam,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Spritefont2.Exps.TagAt,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.Tween.Exps.Progress,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LocalStorage.Cnds.IsProcessingGets,
		C3.Plugins.LocalStorage.Cnds.IsProcessingSets,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Timeline.Cnds.OnKeyframeReached,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Timeline.Cnds.OnAnyTimelineFinished,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.gamepad.Exps.GamepadCount,
		C3.Plugins.gamepad.Cnds.OnAnyButtonUp,
		C3.Plugins.gamepad.Exps.GamepadIndex,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{BinaryData: 0},
	{Keyboard: 0},
	{ArrButtons: 0},
	{Tween: 0},
	{Fader: 0},
	{Gamepad: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{LocalStorage: 0},
	{DictProfile: 0},
	{TimelineController: 0},
	{Audio: 0},
	{shaking: 0},
	{shakeIntensity: 0},
	{speed: 0},
	{Camera: 0},
	{Timer: 0},
	{GameTime: 0},
	{immortal: 0},
	{dead: 0},
	{playedEnterSound: 0},
	{EnemyBoar: 0},
	{EnemyReverse: 0},
	{EnemySpike: 0},
	{wptNum: 0},
	{EnemyWaypoint: 0},
	{EnemyCrow: 0},
	{piranhaStartingDelay: 0},
	{piranhaTimeToDestination: 0},
	{EnemyPiranha: 0},
	{EnemyDeathParticles: 0},
	{nextWpt: 0},
	{EnemyGorilla: 0},
	{playerOffestY: 0},
	{Zipline: 0},
	{ZiplineEnd: 0},
	{SlideZone: 0},
	{tutorialID: 0},
	{TutorialZone: 0},
	{Placeholder: 0},
	{EndOfLevel: 0},
	{Solid: 0},
	{InvisibleWall: 0},
	{L1_Background: 0},
	{L1_Sky: 0},
	{L1_Foreground: 0},
	{L1_Particles: 0},
	{L2_Background: 0},
	{L2_Sky: 0},
	{L2_Foreground: 0},
	{L2_Particles: 0},
	{L3_Background: 0},
	{L3_Sky: 0},
	{L3_Foreground: 0},
	{L4_Background: 0},
	{L4_Sky: 0},
	{L4_Foreground: 0},
	{L4_Particles: 0},
	{L5_Background: 0},
	{L5_Sky: 0},
	{L5_Foreground: 0},
	{dashAvailable: 0},
	{doubleJumping: 0},
	{climbing: 0},
	{ziplining: 0},
	{droppingFromZipline: 0},
	{uncontrollable: 0},
	{Platform: 0},
	{Player: 0},
	{PlayerSprite: 0},
	{PlayerTrail: 0},
	{PlayerDeathParticles: 0},
	{Climber: 0},
	{Ledge: 0},
	{PlayerZiplineGrabber: 0},
	{PlayerAutoJump: 0},
	{PlayerAutoSlide: 0},
	{PlayerAutoDash: 0},
	{TutorialText: 0},
	{Coin: 0},
	{Sine: 0},
	{Building: 0},
	{BuildingDecor: 0},
	{Gong: 0},
	{TileCollision: 0},
	{TileZipline: 0},
	{Chains: 0},
	{EOLBackground: 0},
	{Flash: 0},
	{EOLText: 0},
	{MenuBackground: 0},
	{selectedAction: 0},
	{MenuItemSelector: 0},
	{MenuItemText: 0},
	{MenuAnythingText: 0},
	{MainMenuGroup: 0},
	{MenuGroupAnchor: 0},
	{ResetMenuGroup: 0},
	{MenuBuildings: 0},
	{MenuTitle: 0},
	{MenuPlayerAnim: 0},
	{MenuEntityZones: 0},
	{moveRight: 0},
	{MenuPlayer: 0},
	{doneMoving: 0},
	{MenuCrow: 0},
	{MainMenuManager: 0},
	{MenuSamuraiSprite: 0},
	{MenuFrame: 0},
	{StoryPiece: 0},
	{StoryText: 0},
	{StoryAnythingText: 0},
	{CreditsText: 0},
	{Slowmo: 0},
	{Speedup: 0},
	{EndOfCredits: 0},
	{MoveTo: 0},
	{Enemies: 0},
	{CAMERA_SPEED: 0},
	{CAMERA_SLOW_SPEED: 0},
	{duration: 0},
	{intensity: 0},
	{shake: 0},
	{P_STD_SPEED: 0},
	{P_SLOW_SPEED: 0},
	{P_DASH_COOLDOWN: 0},
	{P_DASH_SPEED: 0},
	{P_SLIDE_COOLDOWN: 0},
	{P_SLIDE_SPEED: 0},
	{P_CLIMB_SPEED: 0},
	{P_ZIP_SPEED: 0},
	{P_GRAVITY: 0},
	{touchStartX: 0},
	{touchStartY: 0},
	{SWIPE_SENSITIVITY: 0},
	{enemyNearby: 0},
	{CROW_TWEEN_TIME: 0},
	{inputMethod: 0},
	{padID: 0},
	{audio: 0},
	{BGMtoPlay: 0},
	{SFXBlock: 0},
	{currentLevel: 0},
	{levelCoins: 0},
	{levelEnemies: 0},
	{levelTime: 0},
	{playerCoins: 0},
	{playerKills: 0},
	{MENUSEQ: 0},
	{RESETSEQ: 0},
	{currItem: 0},
	{currMenu: 0},
	{menuInputEnabled: 0},
	{STORY_0: 0},
	{STORY_1: 0},
	{STORY_2: 0},
	{STORY_3: 0},
	{STORY_SPEED: 0},
	{STORY_DELAY: 0},
	{canProceed: 0},
	{currentStoryPart: 0},
	{storyPart: 0},
	{BGM_VOLUME: 0},
	{BGM_LOW_VOLUME: 0},
	{SFX_VOLUME: 0},
	{name: 0},
	{tag: 0},
	{volumeTweak: 0},
	{pitch: 0},
	{fadeOut: 0},
	{fadeIn: 0},
	{low: 0},
	{forceSilent: 0},
	{in: 0},
	{fadeTime: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	Keyboard: class extends self.IInstance {},
	ArrButtons: class extends self.IArrayInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	Gamepad: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	DictProfile: class extends self.IDictionaryInstance {},
	TimelineController: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Camera: class extends self.ISpriteInstance {},
	GameTime: class extends self.ISpriteInstance {},
	EnemyBoar: class extends self.ISpriteInstance {},
	EnemyReverse: class extends self.ISpriteInstance {},
	EnemySpike: class extends self.ISpriteInstance {},
	EnemyWaypoint: class extends self.ISpriteInstance {},
	EnemyCrow: class extends self.ISpriteInstance {},
	EnemyPiranha: class extends self.ISpriteInstance {},
	EnemyDeathParticles: class extends self.IParticlesInstance {},
	EnemyGorilla: class extends self.ISpriteInstance {},
	Zipline: class extends self.ITiledBackgroundInstance {},
	ZiplineEnd: class extends self.ITiledBackgroundInstance {},
	SlideZone: class extends self.ITiledBackgroundInstance {},
	TutorialZone: class extends self.ITiledBackgroundInstance {},
	Placeholder: class extends self.ISpriteInstance {},
	EndOfLevel: class extends self.ITiledBackgroundInstance {},
	InvisibleWall: class extends self.ITiledBackgroundInstance {},
	L1_Background: class extends self.ITiledBackgroundInstance {},
	L1_Sky: class extends self.ISpriteInstance {},
	L1_Foreground: class extends self.ITiledBackgroundInstance {},
	L1_Particles: class extends self.IParticlesInstance {},
	L2_Background: class extends self.ITiledBackgroundInstance {},
	L2_Sky: class extends self.ISpriteInstance {},
	L2_Foreground: class extends self.ITiledBackgroundInstance {},
	L2_Particles: class extends self.IParticlesInstance {},
	L3_Background: class extends self.ITiledBackgroundInstance {},
	L3_Sky: class extends self.ISpriteInstance {},
	L3_Foreground: class extends self.ITiledBackgroundInstance {},
	L4_Background: class extends self.ITiledBackgroundInstance {},
	L4_Sky: class extends self.ISpriteInstance {},
	L4_Foreground: class extends self.ITiledBackgroundInstance {},
	L4_Particles: class extends self.IParticlesInstance {},
	L5_Background: class extends self.ITiledBackgroundInstance {},
	L5_Sky: class extends self.ISpriteInstance {},
	L5_Foreground: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	PlayerSprite: class extends self.ISpriteInstance {},
	PlayerTrail: class extends self.ISpriteInstance {},
	PlayerDeathParticles: class extends self.IParticlesInstance {},
	Climber: class extends self.ITiledBackgroundInstance {},
	Ledge: class extends self.ITiledBackgroundInstance {},
	PlayerZiplineGrabber: class extends self.ISpriteInstance {},
	PlayerAutoJump: class extends self.ITiledBackgroundInstance {},
	PlayerAutoSlide: class extends self.ITiledBackgroundInstance {},
	PlayerAutoDash: class extends self.ITiledBackgroundInstance {},
	TutorialText: class extends self.ISpriteFontInstance {},
	Coin: class extends self.ISpriteInstance {},
	Building: class extends self.ISpriteInstance {},
	BuildingDecor: class extends self.ISpriteInstance {},
	Gong: class extends self.ISpriteInstance {},
	TileCollision: class extends self.ITilemapInstance {},
	TileZipline: class extends self.ITilemapInstance {},
	Chains: class extends self.ITiledBackgroundInstance {},
	EOLBackground: class extends self.ISpriteInstance {},
	EOLText: class extends self.ISpriteFontInstance {},
	MenuBackground: class extends self.ISpriteInstance {},
	MenuItemSelector: class extends self.ISpriteInstance {},
	MenuItemText: class extends self.ISpriteFontInstance {},
	MenuAnythingText: class extends self.ISpriteFontInstance {},
	MainMenuGroup: class extends self.ISpriteInstance {},
	MenuGroupAnchor: class extends self.ISpriteInstance {},
	ResetMenuGroup: class extends self.ISpriteInstance {},
	MenuBuildings: class extends self.ISpriteInstance {},
	MenuTitle: class extends self.ISpriteInstance {},
	MenuPlayerAnim: class extends self.ISpriteInstance {},
	MenuEntityZones: class extends self.ISpriteInstance {},
	MenuPlayer: class extends self.ISpriteInstance {},
	MenuCrow: class extends self.ISpriteInstance {},
	MainMenuManager: class extends self.ISpriteInstance {},
	MenuSamuraiSprite: class extends self.ISpriteInstance {},
	MenuFrame: class extends self.ISpriteInstance {},
	StoryPiece: class extends self.ISpriteInstance {},
	StoryText: class extends self.ISpriteFontInstance {},
	StoryAnythingText: class extends self.ISpriteFontInstance {},
	CreditsText: class extends self.ISpriteFontInstance {},
	Slowmo: class extends self.ITiledBackgroundInstance {},
	Speedup: class extends self.ITiledBackgroundInstance {},
	EndOfCredits: class extends self.ITiledBackgroundInstance {},
	Enemies: class extends self.ISpriteInstance {}
}