const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Shape3D,
		C3.Behaviors.Tween,
		C3.Plugins.Model3D,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Plugins.Arr,
		C3.Plugins.Dictionary,
		C3.Plugins.Camera3D,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Keyboard,
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.AdvancedRandom,
		C3.Behaviors.Flash,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.trim,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Shape3D.Cnds.PickChildren,
		C3.Plugins.System.Exps.max,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.SetLayerEffectParam,
		C3.Plugins.System.Exps.rgbex255,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.TiledBg.Acts.SetEffectParam,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Shape3D.Cnds.IsVisible,
		C3.Plugins.Shape3D.Acts.SetVisible,
		C3.Plugins.Shape3D.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Sprite.Exps.TagAt,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.RecreateInitialObjects,
		C3.Plugins.System.Exps.hexcolor,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Z,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Camera3D.Acts.SetPosition,
		C3.Plugins.Camera3D.Exps.CameraZ,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Camera3D.Acts.MoveAlongCameraAxis,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.RestoreObjectTimescale,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Exps.min,
		C3.Plugins.TiledBg.Exps.ImageHeight,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Camera3D.Exps.CanvasToLayerX,
		C3.Plugins.Touch.Exps.AbsoluteX,
		C3.Plugins.Touch.Exps.AbsoluteY,
		C3.Plugins.Shape3D.Exps.Z,
		C3.Plugins.Camera3D.Exps.CanvasToLayerY,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Cnds.PickParent,
		C3.Plugins.Camera3D.Exps.LayerToCanvasX,
		C3.Plugins.PlatformInfo.Exps.CanvasCssWidth,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.Camera3D.Exps.LayerToCanvasY,
		C3.Plugins.PlatformInfo.Exps.CanvasCssHeight,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.System.Exps.distance3d,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Behaviors.Sin.Exps.Value,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Exps.Depth,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Shape3D.Acts.SetSize,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Model3D.Acts.SetModelByName,
		C3.Plugins.Model3D.Acts.SetSize3D,
		C3.Plugins.Model3D.Acts.SetTransform,
		C3.Plugins.System.Exps.float,
		C3.Plugins.Shape3D.Acts.SetDefaultColor,
		C3.Plugins.Shape3D.Exps.ColorValue,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.Tween.Acts.PauseTweens,
		C3.Behaviors.Tween.Acts.ResumeAllTweens,
		C3.Plugins.Text.Cnds.PickParent,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Arr.Cnds.CompareXYZ,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Model3D.Acts.SetDefaultColor,
		C3.Plugins.Model3D.Acts.SetModel,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.Shape3D.Acts.SetWidth,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Model3D.Acts.SetPosToObject,
		C3.Plugins.Model3D.Acts.SetAngle,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Model3D.Acts.SetVisible,
		C3.Plugins.Model3D.Acts.SetAllMeshesEnabled,
		C3.Plugins.Shape3D.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Shape3D.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Plugins.AdvancedRandom.Acts.ShufflePermutationTable,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Arr.Acts.SetX,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.DragnDrop.Acts.Drop,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.HasChildren,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.LocalStorage.Cnds.IsProcessingGets,
		C3.Plugins.LocalStorage.Cnds.IsProcessingSets,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Audio.Exps.Volume,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Model3D.Acts.SetZ,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Plugins.Model3D.Acts.SetInstanceVar,
		C3.Plugins.Model3D.Acts.SetPos,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Model3D.Exps.X,
		C3.Plugins.Model3D.Exps.Y,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Model3D.Acts.Destroy,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Model3D.Acts.SetY,
		C3.Plugins.Text.Exps.TagAt,
		C3.Plugins.Text.Cnds.CompareY,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.colortohexstring,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Dictionary.Acts.SetKey
	];
};
self.C3_JsPropNameTable = [
	{nodeID: 0},
	{player: 0},
	{enemy: 0},
	{inLinks: 0},
	{outLinks: 0},
	{inProgress: 0},
	{hidden: 0},
	{unidentified: 0},
	{suspicion: 0},
	{credits: 0},
	{softwareCapturing: 0},
	{EntryNode: 0},
	{RelayNode: 0},
	{Tween: 0},
	{NodeBase: 0},
	{angles: 0},
	{size: 0},
	{Rotate: 0},
	{Sine: 0},
	{NodeModel: 0},
	{BinaryNode: 0},
	{GoalNode: 0},
	{EncryptedNode: 0},
	{FirewallNode: 0},
	{TracerNode: 0},
	{HoneypotNode: 0},
	{HunterNode: 0},
	{DataNode: 0},
	{IntelNode: 0},
	{BandwidthNode: 0},
	{GenericNode: 0},
	{linkedTo: 0},
	{BackdoorNode: 0},
	{linkID: 0},
	{fromID: 0},
	{toID: 0},
	{direction: 0},
	{Link: 0},
	{LinkDirection3D: 0},
	{BackgroundGrid: 0},
	{UI_CPUMeter: 0},
	{UI_ProgressBG: 0},
	{UI_TraceMeter: 0},
	{UI_MiscText: 0},
	{UI_Selection: 0},
	{UI_SelectionGroup: 0},
	{UI_SelectionText: 0},
	{UI_InfoText: 0},
	{startingFaceSize: 0},
	{UI_EMPText: 0},
	{UI_TutorialFader: 0},
	{enabled: 0},
	{UI_TutorialStart: 0},
	{UI_TutorialStartText: 0},
	{UI_TutorialText: 0},
	{UI_PauseMenuButton: 0},
	{UI_PauseFader: 0},
	{UI_MenuButton: 0},
	{UI_GameOver: 0},
	{UI_GameOverText: 0},
	{UI_GOMiscText: 0},
	{UI_LevelCreditsText: 0},
	{UI_DataCreditsText: 0},
	{UI_GameOverFader: 0},
	{UI_SoftwareBar: 0},
	{UI_SoftwareBarSprite: 0},
	{UI_SoftwareCount: 0},
	{software: 0},
	{exploit: 0},
	{qty: 0},
	{Timer: 0},
	{UI_SoftwareItem: 0},
	{UI_GameFader: 0},
	{LightBeam: 0},
	{retryInterval: 0},
	{captureTime: 0},
	{nextCaptureInterval: 0},
	{EnemyManager: 0},
	{ArrLevel: 0},
	{ArrSoftware: 0},
	{ArrLoadout: 0},
	{DictNodeDesc: 0},
	{DictRewards: 0},
	{DictProfile: 0},
	{"3DCamera": 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{Keyboard: 0},
	{AJAX: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{AdvancedRandom: 0},
	{Shop_MiscText: 0},
	{Shop_SoftDesc: 0},
	{Shop_SoftName: 0},
	{Shop_Software: 0},
	{Shop_Purchase: 0},
	{Shop_Selection: 0},
	{Shop_SoftAmt: 0},
	{Shop_PlayerCredits: 0},
	{Shop_Back: 0},
	{Shop_Background: 0},
	{Shop_SoftPrice: 0},
	{Main_Arrows: 0},
	{Main_Background: 0},
	{Main_Play: 0},
	{Main_Settings: 0},
	{Main_Shop: 0},
	{Flash: 0},
	{Main_DescText: 0},
	{Main_LevelNo: 0},
	{Main_MiscText: 0},
	{Main_Selection: 0},
	{Main_Slot: 0},
	{startingX: 0},
	{startingY: 0},
	{instances: 0},
	{DragDrop: 0},
	{Main_Software: 0},
	{Main_ThumbnailMask: 0},
	{Main_WhiteFader: 0},
	{Main_SoftwareCount: 0},
	{Main_SlotBruteforce: 0},
	{Main_BlackFader: 0},
	{Main_Thumbnail: 0},
	{Settings_Fader: 0},
	{Settings_Button: 0},
	{Settings_DescText: 0},
	{Title_DoAnythingText: 0},
	{Title_Background: 0},
	{Title_BackgroundFader: 0},
	{Title_Display: 0},
	{Title_LED: 0},
	{Title_Light: 0},
	{Title_Mask: 0},
	{Title_Scanlines: 0},
	{Title_ScreenAnim: 0},
	{Title_ScreenContent: 0},
	{Title_TopFader: 0},
	{Title_Vignette: 0},
	{Credits_Text: 0},
	{Credits_Fader: 0},
	{rotX: 0},
	{rotY: 0},
	{rotZ: 0},
	{MoveTo: 0},
	{Credits_Model: 0},
	{CreditsManager: 0},
	{Nodes: 0},
	{Links: 0},
	{pickedEnemyNodeID: 0},
	{validNodes: 0},
	{linkedNodes: 0},
	{currentPair: 0},
	{validMoves: 0},
	{randomChoice: 0},
	{chosenMove: 0},
	{chosenNode: 0},
	{chosenLink: 0},
	{connectedLinks: 0},
	{currNodeAndLink: 0},
	{currLink: 0},
	{enemyBandwidthRatio: 0},
	{nodeHardnessRatio: 0},
	{detected: 0},
	{gameOver: 0},
	{paused: 0},
	{tutorial: 0},
	{overclockBandwidth: 0},
	{maxConcurrency: 0},
	{level: 0},
	{selectedNodeID: 0},
	{camPanSpeed: 0},
	{camDragStartX: 0},
	{camDragStartY: 0},
	{camVelX: 0},
	{camVelY: 0},
	{camFocus: 0},
	{CAMERA_HEIGHT: 0},
	{CAMERA_DIST: 0},
	{CAMERA_RADIUS: 0},
	{PLAYER_COLOR: 0},
	{PLAYER_COLOR_DARK: 0},
	{ENEMY_COLOR: 0},
	{ENEMY_COLOR_UI: 0},
	{ENEMY_COLOR_DARK: 0},
	{NEUTRAL_COLOR: 0},
	{BANDWIDTH_RATIO: 0},
	{UNKNOWN_MODEL_SIZE: 0},
	{RW_SUSPICION_RATIO: 0},
	{STH_SUSPICION_RATIO: 0},
	{XPT_SUSPICION_RATIO: 0},
	{TRACER_SUSPICION_RATIO: 0},
	{LINK_MORPH_TIME: 0},
	{EMP_TIME: 0},
	{softwareName: 0},
	{dx: 0},
	{dy: 0},
	{dist: 0},
	{scale: 0},
	{localX: 0},
	{localY: 0},
	{targetX: 0},
	{targetY: 0},
	{TRACE_METER_SIZE: 0},
	{CPU_METER_SIZE: 0},
	{MAX_SELECTION_DIST: 0},
	{totalLevelCredits: 0},
	{totalDataCredits: 0},
	{win: 0},
	{message: 0},
	{isError: 0},
	{tracerSuspicionRatio: 0},
	{checkingPlayerNode: 0},
	{checkingEnemyNode: 0},
	{firewallNeighbors: 0},
	{tracerNeighbors: 0},
	{playerNodes: 0},
	{nodeLinkToken: 0},
	{linkedNodesStr: 0},
	{enemyNodes: 0},
	{notInProgressNodes: 0},
	{team: 0},
	{morphTime: 0},
	{linksCount: 0},
	{fromNode: 0},
	{fromX: 0},
	{fromY: 0},
	{toNode: 0},
	{toX: 0},
	{toY: 0},
	{typeA: 0},
	{typeB: 0},
	{total: 0},
	{softwareSuspicionRatio: 0},
	{desc: 0},
	{nodesAndLinks: 0},
	{currNode: 0},
	{softwareCapTime: 0},
	{playerBandwidthRatio: 0},
	{playerOverclockRatio: 0},
	{mainMenuEnabled: 0},
	{settingsScreen: 0},
	{shopScreen: 0},
	{selectedLevel: 0},
	{checkArrLoadout: 0},
	{softwareUID: 0},
	{selectedShopSoft: 0},
	{dragging: 0},
	{BGMPlayed: 0},
	{SFXBlock: 0},
	{BGM_VOLUME: 0},
	{BGM_LOW_VOLUME: 0},
	{SFX_VOLUME: 0},
	{low: 0},
	{name: 0},
	{tag: 0},
	{volumeTweak: 0},
	{pitch: 0},
	{forceSilent: 0},
	{in: 0},
	{fadeTime: 0},
	{CREDITS_SPEED: 0},
	{rnd: 0},
	{r: 0},
	{value: 0}
];

self.InstanceType = {
	EntryNode: class extends self.ISpriteInstance {},
	RelayNode: class extends self.ISpriteInstance {},
	NodeBase: class extends self.I3DShapeInstance {},
	NodeModel: class extends self.I3DModelInstance {},
	BinaryNode: class extends self.ISpriteInstance {},
	GoalNode: class extends self.ISpriteInstance {},
	EncryptedNode: class extends self.ISpriteInstance {},
	FirewallNode: class extends self.ISpriteInstance {},
	TracerNode: class extends self.ISpriteInstance {},
	HoneypotNode: class extends self.ISpriteInstance {},
	HunterNode: class extends self.ISpriteInstance {},
	DataNode: class extends self.ISpriteInstance {},
	IntelNode: class extends self.ISpriteInstance {},
	BandwidthNode: class extends self.ISpriteInstance {},
	GenericNode: class extends self.ISpriteInstance {},
	BackdoorNode: class extends self.ISpriteInstance {},
	Link: class extends self.I3DShapeInstance {},
	LinkDirection3D: class extends self.I3DModelInstance {},
	BackgroundGrid: class extends self.ITiledBackgroundInstance {},
	UI_CPUMeter: class extends self.ITiledBackgroundInstance {},
	UI_ProgressBG: class extends self.I9PatchInstance {},
	UI_TraceMeter: class extends self.ITiledBackgroundInstance {},
	UI_MiscText: class extends self.ITextInstance {},
	UI_Selection: class extends self.ISpriteInstance {},
	UI_SelectionGroup: class extends self.ISpriteInstance {},
	UI_SelectionText: class extends self.ITextInstance {},
	UI_InfoText: class extends self.ITextInstance {},
	UI_EMPText: class extends self.ITextInstance {},
	UI_TutorialFader: class extends self.ITiledBackgroundInstance {},
	UI_TutorialStart: class extends self.ISpriteInstance {},
	UI_TutorialStartText: class extends self.ITextInstance {},
	UI_TutorialText: class extends self.ITextInstance {},
	UI_PauseMenuButton: class extends self.ISpriteInstance {},
	UI_PauseFader: class extends self.ITiledBackgroundInstance {},
	UI_MenuButton: class extends self.ISpriteInstance {},
	UI_GameOver: class extends self.ISpriteInstance {},
	UI_GameOverText: class extends self.ITextInstance {},
	UI_GOMiscText: class extends self.ITextInstance {},
	UI_LevelCreditsText: class extends self.ITextInstance {},
	UI_DataCreditsText: class extends self.ITextInstance {},
	UI_GameOverFader: class extends self.ITiledBackgroundInstance {},
	UI_SoftwareBar: class extends self.ITiledBackgroundInstance {},
	UI_SoftwareBarSprite: class extends self.ISpriteInstance {},
	UI_SoftwareCount: class extends self.ITextInstance {},
	UI_SoftwareItem: class extends self.ISpriteInstance {},
	UI_GameFader: class extends self.ITiledBackgroundInstance {},
	LightBeam: class extends self.I3DShapeInstance {},
	EnemyManager: class extends self.ISpriteInstance {},
	ArrLevel: class extends self.IArrayInstance {},
	ArrSoftware: class extends self.IArrayInstance {},
	ArrLoadout: class extends self.IArrayInstance {},
	DictNodeDesc: class extends self.IDictionaryInstance {},
	DictRewards: class extends self.IDictionaryInstance {},
	DictProfile: class extends self.IDictionaryInstance {},
	_3DCamera: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AdvancedRandom: class extends self.IInstance {},
	Shop_MiscText: class extends self.ITextInstance {},
	Shop_SoftDesc: class extends self.ITextInstance {},
	Shop_SoftName: class extends self.ITextInstance {},
	Shop_Software: class extends self.ISpriteInstance {},
	Shop_Purchase: class extends self.ISpriteInstance {},
	Shop_Selection: class extends self.ISpriteInstance {},
	Shop_SoftAmt: class extends self.ITextInstance {},
	Shop_PlayerCredits: class extends self.ITextInstance {},
	Shop_Back: class extends self.ISpriteInstance {},
	Shop_Background: class extends self.ISpriteInstance {},
	Shop_SoftPrice: class extends self.ITextInstance {},
	Main_Arrows: class extends self.ISpriteInstance {},
	Main_Background: class extends self.ISpriteInstance {},
	Main_Play: class extends self.ISpriteInstance {},
	Main_Settings: class extends self.ISpriteInstance {},
	Main_Shop: class extends self.ISpriteInstance {},
	Main_DescText: class extends self.ITextInstance {},
	Main_LevelNo: class extends self.ITextInstance {},
	Main_MiscText: class extends self.ITextInstance {},
	Main_Selection: class extends self.ISpriteInstance {},
	Main_Slot: class extends self.ISpriteInstance {},
	Main_Software: class extends self.ISpriteInstance {},
	Main_ThumbnailMask: class extends self.ISpriteInstance {},
	Main_WhiteFader: class extends self.ITiledBackgroundInstance {},
	Main_SoftwareCount: class extends self.ITextInstance {},
	Main_SlotBruteforce: class extends self.ISpriteInstance {},
	Main_BlackFader: class extends self.ITiledBackgroundInstance {},
	Main_Thumbnail: class extends self.ISpriteInstance {},
	Settings_Fader: class extends self.ITiledBackgroundInstance {},
	Settings_Button: class extends self.ISpriteInstance {},
	Settings_DescText: class extends self.ITextInstance {},
	Title_DoAnythingText: class extends self.ITextInstance {},
	Title_Background: class extends self.ITiledBackgroundInstance {},
	Title_BackgroundFader: class extends self.ITiledBackgroundInstance {},
	Title_Display: class extends self.ISpriteInstance {},
	Title_LED: class extends self.ISpriteInstance {},
	Title_Light: class extends self.ISpriteInstance {},
	Title_Mask: class extends self.ISpriteInstance {},
	Title_Scanlines: class extends self.ITiledBackgroundInstance {},
	Title_ScreenAnim: class extends self.ISpriteInstance {},
	Title_ScreenContent: class extends self.ISpriteInstance {},
	Title_TopFader: class extends self.ITiledBackgroundInstance {},
	Title_Vignette: class extends self.ISpriteInstance {},
	Credits_Text: class extends self.ITextInstance {},
	Credits_Fader: class extends self.ITiledBackgroundInstance {},
	Credits_Model: class extends self.I3DModelInstance {},
	CreditsManager: class extends self.ISpriteInstance {},
	Nodes: class extends self.ISpriteInstance {},
	Links: class extends self.I3DShapeInstance {}
}