const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.custom,
		C3.Behaviors.bound,
		C3.Behaviors.Timer,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.destroy,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Dictionary,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Timeline,
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.Particles,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Cnds.HasTags,
		C3.Plugins.System.Acts.SetLayerEffectEnabled,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Timeline.Cnds.OnKeyframeReached,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.TiledBg.Exps.BBoxTop,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Acts.SetLayerEffectParam,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.TiledBg.Exps.ImageWidth,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Dictionary.Cnds.ForEachKey,
		C3.Plugins.Dictionary.Exps.CurrentValue,
		C3.Plugins.Dictionary.Exps.CurrentKey,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.LocalStorage.Cnds.IsProcessingGets,
		C3.Plugins.LocalStorage.Cnds.IsProcessingSets,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Timer.Acts.PauseResumeAllTimers,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.scrolly,
		C3.Behaviors.custom.Exps.dy,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Exps.TemplateName,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Sin.Exps.Value,
		C3.Behaviors.custom.Acts.Accelerate,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Acts.LoadLayoutTextures,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Timeline.Cnds.OnTimelineFinishedByTags,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Touch.Exps.TouchCount,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba255,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.TiledBg.Exps.Count,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.TiledBg.Acts.SetPosToObject,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.TiledBg.Cnds.PickParent,
		C3.Behaviors.custom.Acts.SetEnabled,
		C3.Behaviors.custom.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Dictionary.Acts.DeleteKey,
		C3.Behaviors.custom.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Behaviors.custom.Exps.dx,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.MoveTo.Exps.Speed,
		C3.Behaviors.MoveTo.Exps.TargetX,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Cnds.IsTagPlaying
	];
};
self.C3_JsPropNameTable = [
	{rotSpeed: 0},
	{Custom: 0},
	{BoundToLayout: 0},
	{Timer: 0},
	{Tween: 0},
	{Player: 0},
	{sphereUID: 0},
	{PlayerLink: 0},
	{Sine: 0},
	{PlayerSprite: 0},
	{Rotate: 0},
	{PlayerWheel: 0},
	{inPool: 0},
	{PlayerTrail: 0},
	{explosionType: 0},
	{addToScore: 0},
	{Drone: 0},
	{Blaster: 0},
	{Saucer: 0},
	{Recon: 0},
	{ReconWheels: 0},
	{BlasterCoil: 0},
	{DroneDoorBack: 0},
	{Boss: 0},
	{BossOrganic: 0},
	{Sky0: 0},
	{Sky1: 0},
	{Sky2: 0},
	{Sky3: 0},
	{Road0: 0},
	{Road1: 0},
	{Road2: 0},
	{Road3: 0},
	{Parallax0_0: 0},
	{Parallax0_1: 0},
	{Parallax0_2: 0},
	{Parallax0_3: 0},
	{Parallax1_0: 0},
	{Parallax1_1: 0},
	{Parallax1_2: 0},
	{Parallax1_3: 0},
	{Parallax2_0: 0},
	{Parallax2_1: 0},
	{velocityX: 0},
	{DestroyOutsideLayout: 0},
	{Bomb: 0},
	{PowerX: 0},
	{PowerY: 0},
	{Explosion: 0},
	{angleOfMotion: 0},
	{Bullet: 0},
	{EnergySphere: 0},
	{SaucerAbductor: 0},
	{MuzzleFlash: 0},
	{Keyboard: 0},
	{DictCombo: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{TimelineController: 0},
	{AJAX: 0},
	{DictProfile: 0},
	{LocalStorage: 0},
	{ArrScenery: 0},
	{Audio: 0},
	{ArrBGM: 0},
	{GameManager: 0},
	{buttonID: 0},
	{ButtonBuy: 0},
	{textID: 0},
	{TextBuyItem: 0},
	{TextShopTitle: 0},
	{TextUpgradePoints: 0},
	{ShopBackground: 0},
	{ButtonCancel: 0},
	{ButtonExit: 0},
	{InGameMenu: 0},
	{TextExitConfirm: 0},
	{ButtonLink: 0},
	{ButtonRocket: 0},
	{AnalogBase: 0},
	{AnalogStick: 0},
	{ButtonSound: 0},
	{ButtonPause: 0},
	{TextBestCombo: 0},
	{TextCombo: 0},
	{Flash: 0},
	{TextNewBest: 0},
	{TextScore: 0},
	{TimeBar: 0},
	{TimeBarBottom: 0},
	{TextFail: 0},
	{TextMissionStart: 0},
	{tt_bgrocks0_0: 0},
	{tt_bomb: 0},
	{tt_bomb_light: 0},
	{tt_bomb_smoke: 0},
	{tt_buildings0: 0},
	{tt_fgrocks: 0},
	{tt_floor0: 0},
	{tt_rover: 0},
	{tt_rover_lights: 0},
	{tt_saucer: 0},
	{tt_saucer_details: 0},
	{tt_saucer_light: 0},
	{tt_shadows: 0},
	{tt_sky0: 0},
	{tt_text0: 0},
	{tt_text1: 0},
	{tt_vignette0: 0},
	{tt_vignette1: 0},
	{ButtonMenu: 0},
	{Fader: 0},
	{TextMenuInstructions: 0},
	{TextMenuInteract: 0},
	{TextMenuItem: 0},
	{Sine2: 0},
	{MenuManager: 0},
	{Subfader: 0},
	{MainMenuBackground: 0},
	{Particles: 0},
	{playedSound: 0},
	{Obstacle: 0},
	{ObstacleTrail: 0},
	{DarknessSprite: 0},
	{TextTutorial: 0},
	{TutorialBackground: 0},
	{CreditsGradient: 0},
	{TextCredits: 0},
	{Explosives: 0},
	{Roads: 0},
	{Parallax0: 0},
	{Parallax1: 0},
	{Static: 0},
	{MoveTo: 0},
	{Enemies: 0},
	{Parallax2: 0},
	{TARGET_SCORE: 0},
	{ENDLESS_TIME_LIMIT: 0},
	{CAMPAIGN_TIME_LIMIT: 0},
	{IGMButtonSelected: 0},
	{inputFocus: 0},
	{currentLevel: 0},
	{timeRemaining: 0},
	{playerScore: 0},
	{comboScore: 0},
	{bestComboScore: 0},
	{targetScore: 0},
	{lockScore: 0},
	{windy: 0},
	{timeLimit: 0},
	{canRocket: 0},
	{canLink: 0},
	{canBounce: 0},
	{eLevelDrone: 0},
	{eLevelBlaster: 0},
	{eLevelSaucer: 0},
	{eLevelRecon: 0},
	{groundLevel: 0},
	{BG_PARALLAX_0: 0},
	{BG_PARALLAX_1: 0},
	{BG_PARALLAX_2: 0},
	{level: 0},
	{MULTIPLIER_ADD: 0},
	{SCORE_ADD: 0},
	{COMBO_FONT_SIZE: 0},
	{SCORE_FONT_SIZE: 0},
	{DRONE_COLOR: 0},
	{BLASTER_COLOR: 0},
	{SAUCER_COLOR: 0},
	{RECON_COLOR: 0},
	{BOSS_COLOR: 0},
	{multiplier: 0},
	{totalScore: 0},
	{addPlus: 0},
	{useMultiplier: 0},
	{score: 0},
	{fromShop: 0},
	{animate: 0},
	{MIN_SPHERE_Y: 0},
	{BOMB_VERTICAL_SPEED: 0},
	{menuButtonSelected: 0},
	{menuFocus: 0},
	{endlessMode: 0},
	{mobileControls: 0},
	{LAYER_SCALE: 0},
	{pTouchX: 0},
	{pTouchY: 0},
	{PLAYER_BOUNCE_THRESHOLD: 0},
	{PLAYER_REBOUND_STRENGTH: 0},
	{PLAYER_X_ACCELERATION: 0},
	{PLAYER_X_BRAKE: 0},
	{PLAYER_X_GROUND_DRAG: 0},
	{PLAYER_X_AIRBORNE_DRAG: 0},
	{PLAYER_X_WIND: 0},
	{PLAYER_GRAVITY: 0},
	{PLAYER_MAX_X_SPEED: 0},
	{Xaxis: 0},
	{color: 0},
	{E_SPAWN_OFFSET_X: 0},
	{E_SPAWN_OFFSET_Y: 0},
	{E_SPAWN_MIN_Y: 0},
	{E_SPAWN_MAX_Y: 0},
	{E_SPAWN_NO_RECON: 0},
	{E_SPAWN_BASE_TIME: 0},
	{E_SPAWN_DEC_TIME: 0},
	{shopButtonSelected: 0},
	{FIRST_PURCHASE: 0},
	{BASE_PRICE: 0},
	{LEVEL_TAX: 0},
	{upgradeLevels: 0},
	{type: 0},
	{upgradeLevel: 0},
	{tutorialFocus: 0},
	{OFFSET: 0},
	{BGM_VOLUME: 0},
	{BGM_LOW_VOLUME: 0},
	{SFX_VOLUME: 0},
	{BGMPlayed: 0},
	{SFXBlock: 0},
	{name: 0},
	{tag: 0},
	{volumeTweak: 0},
	{pitch: 0},
	{fadeOut: 0},
	{fadeIn: 0},
	{low: 0},
	{forceSilent: 0},
	{in: 0},
	{fadeTime: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	PlayerLink: class extends self.ITiledBackgroundInstance {},
	PlayerSprite: class extends self.ISpriteInstance {},
	PlayerWheel: class extends self.ISpriteInstance {},
	PlayerTrail: class extends self.ISpriteInstance {},
	Drone: class extends self.ISpriteInstance {},
	Blaster: class extends self.ISpriteInstance {},
	Saucer: class extends self.ISpriteInstance {},
	Recon: class extends self.ISpriteInstance {},
	ReconWheels: class extends self.ISpriteInstance {},
	BlasterCoil: class extends self.ISpriteInstance {},
	DroneDoorBack: class extends self.ISpriteInstance {},
	Boss: class extends self.ISpriteInstance {},
	BossOrganic: class extends self.ISpriteInstance {},
	Sky0: class extends self.ITiledBackgroundInstance {},
	Sky1: class extends self.ITiledBackgroundInstance {},
	Sky2: class extends self.ITiledBackgroundInstance {},
	Sky3: class extends self.ITiledBackgroundInstance {},
	Road0: class extends self.ITiledBackgroundInstance {},
	Road1: class extends self.ITiledBackgroundInstance {},
	Road2: class extends self.ITiledBackgroundInstance {},
	Road3: class extends self.ITiledBackgroundInstance {},
	Parallax0_0: class extends self.ITiledBackgroundInstance {},
	Parallax0_1: class extends self.ITiledBackgroundInstance {},
	Parallax0_2: class extends self.ITiledBackgroundInstance {},
	Parallax0_3: class extends self.ITiledBackgroundInstance {},
	Parallax1_0: class extends self.ITiledBackgroundInstance {},
	Parallax1_1: class extends self.ITiledBackgroundInstance {},
	Parallax1_2: class extends self.ITiledBackgroundInstance {},
	Parallax1_3: class extends self.ITiledBackgroundInstance {},
	Parallax2_0: class extends self.ITiledBackgroundInstance {},
	Parallax2_1: class extends self.ITiledBackgroundInstance {},
	Bomb: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	EnergySphere: class extends self.ISpriteInstance {},
	SaucerAbductor: class extends self.ISpriteInstance {},
	MuzzleFlash: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	DictCombo: class extends self.IDictionaryInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	TimelineController: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	DictProfile: class extends self.IDictionaryInstance {},
	LocalStorage: class extends self.IInstance {},
	ArrScenery: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	ArrBGM: class extends self.IArrayInstance {},
	GameManager: class extends self.ISpriteInstance {},
	ButtonBuy: class extends self.ISpriteInstance {},
	TextBuyItem: class extends self.ITextInstance {},
	TextShopTitle: class extends self.ITextInstance {},
	TextUpgradePoints: class extends self.ITextInstance {},
	ShopBackground: class extends self.ISpriteInstance {},
	ButtonCancel: class extends self.ISpriteInstance {},
	ButtonExit: class extends self.ISpriteInstance {},
	InGameMenu: class extends self.ISpriteInstance {},
	TextExitConfirm: class extends self.ITextInstance {},
	ButtonLink: class extends self.ISpriteInstance {},
	ButtonRocket: class extends self.ISpriteInstance {},
	AnalogBase: class extends self.ISpriteInstance {},
	AnalogStick: class extends self.ISpriteInstance {},
	ButtonSound: class extends self.ISpriteInstance {},
	ButtonPause: class extends self.ISpriteInstance {},
	TextBestCombo: class extends self.ITextInstance {},
	TextCombo: class extends self.ITextInstance {},
	TextNewBest: class extends self.ITextInstance {},
	TextScore: class extends self.ITextInstance {},
	TimeBar: class extends self.ITiledBackgroundInstance {},
	TimeBarBottom: class extends self.ITiledBackgroundInstance {},
	TextFail: class extends self.ITextInstance {},
	TextMissionStart: class extends self.ITextInstance {},
	tt_bgrocks0_0: class extends self.ISpriteInstance {},
	tt_bomb: class extends self.ISpriteInstance {},
	tt_bomb_light: class extends self.ISpriteInstance {},
	tt_bomb_smoke: class extends self.ISpriteInstance {},
	tt_buildings0: class extends self.ISpriteInstance {},
	tt_fgrocks: class extends self.ISpriteInstance {},
	tt_floor0: class extends self.ISpriteInstance {},
	tt_rover: class extends self.ISpriteInstance {},
	tt_rover_lights: class extends self.ISpriteInstance {},
	tt_saucer: class extends self.ISpriteInstance {},
	tt_saucer_details: class extends self.ISpriteInstance {},
	tt_saucer_light: class extends self.ISpriteInstance {},
	tt_shadows: class extends self.ISpriteInstance {},
	tt_sky0: class extends self.ISpriteInstance {},
	tt_text0: class extends self.ISpriteInstance {},
	tt_text1: class extends self.ISpriteInstance {},
	tt_vignette0: class extends self.ISpriteInstance {},
	tt_vignette1: class extends self.ISpriteInstance {},
	ButtonMenu: class extends self.ISpriteInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	TextMenuInstructions: class extends self.ITextInstance {},
	TextMenuInteract: class extends self.ITextInstance {},
	TextMenuItem: class extends self.ITextInstance {},
	MenuManager: class extends self.ISpriteInstance {},
	Subfader: class extends self.ITiledBackgroundInstance {},
	MainMenuBackground: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Obstacle: class extends self.ISpriteInstance {},
	ObstacleTrail: class extends self.ISpriteInstance {},
	DarknessSprite: class extends self.ISpriteInstance {},
	TextTutorial: class extends self.ITextInstance {},
	TutorialBackground: class extends self.ISpriteInstance {},
	CreditsGradient: class extends self.ITiledBackgroundInstance {},
	TextCredits: class extends self.ITextInstance {},
	Explosives: class extends self.ISpriteInstance {},
	Roads: class extends self.ITiledBackgroundInstance {},
	Parallax0: class extends self.ITiledBackgroundInstance {},
	Parallax1: class extends self.ITiledBackgroundInstance {},
	Static: class extends self.ISpriteInstance {},
	Enemies: class extends self.ISpriteInstance {},
	Parallax2: class extends self.ITiledBackgroundInstance {}
}