const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Behaviors.Turret,
		C3.Behaviors.Flash,
		C3.Plugins.Spritefont2,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.AJAX,
		C3.Plugins.Dictionary,
		C3.Plugins.Touch,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.PlatformInfo,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Exps.TagAt,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.float,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.AdvancedRandom.Acts.CreateProbabilityTable,
		C3.Plugins.AdvancedRandom.Acts.AddProbabilityEntry,
		C3.Plugins.AdvancedRandom.Exps.Weighted,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Spritefont2.Exps.TagAt,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.ChangeTags,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Mouse.Exps.AbsoluteX,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceWidth,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.NinePatch.Cnds.CompareOpacity,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.RestoreObjectTimescale,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.LocalStorage.Cnds.IsProcessingGets,
		C3.Plugins.LocalStorage.Cnds.IsProcessingSets,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Turret.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Behaviors.Timer.Exps.NormalizedProgress,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Behaviors.Timer.Exps.TotalTime,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.TiledBg.Exps.TagAt,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Cnds.IsTagPlaying
	];
};
self.C3_JsPropNameTable = [
	{BasePlayer: 0},
	{Tween: 0},
	{BaseSprite: 0},
	{spot0: 0},
	{spot1: 0},
	{spot2: 0},
	{TurretSpotsPlayer: 0},
	{Timer: 0},
	{BaseCPU: 0},
	{BaseSpotMarker: 0},
	{civilization: 0},
	{spot: 0},
	{damage: 0},
	{projectile: 0},
	{projectileHit: 0},
	{castEffect: 0},
	{Turret: 0},
	{TurretSpotsCPU: 0},
	{CPUSpawner: 0},
	{PlayerSpawner: 0},
	{BaseSpriteFront: 0},
	{BaseBed: 0},
	{TurretCPU: 0},
	{age: 0},
	{moveSpeed: 0},
	{attacking: 0},
	{hp: 0},
	{cooldown: 0},
	{range: 0},
	{pendingDeath: 0},
	{Civ0Melee: 0},
	{Civ0Ranged: 0},
	{Civ0Super: 0},
	{Civ1Melee: 0},
	{Civ1Ranged: 0},
	{Civ1Super: 0},
	{Flash: 0},
	{UnitDeathAnim: 0},
	{Civ0UnitTarget: 0},
	{Civ1UnitTarget: 0},
	{Parallax0: 0},
	{Parallax1: 0},
	{Foreground: 0},
	{Sky: 0},
	{enabled: 0},
	{UIIcon: 0},
	{UITextDescription: 0},
	{unit: 0},
	{UIQueue: 0},
	{UITextAge: 0},
	{UIProgress: 0},
	{UIProgressBackground: 0},
	{UIMenuArea: 0},
	{UIGameArea: 0},
	{UIHealthBackground: 0},
	{UIHealth: 0},
	{UITextFunds: 0},
	{UITextGold: 0},
	{SpecialProgress: 0},
	{UITextClock: 0},
	{UIDecoration: 0},
	{Fader: 0},
	{UIWinDefeat: 0},
	{UIMenuText: 0},
	{worksPaused: 0},
	{UICancelButton: 0},
	{UIConfirmButton: 0},
	{UIMenuFrame: 0},
	{UIPauseButton: 0},
	{UIToggleSoundButton: 0},
	{UITutorialButton: 0},
	{UITutorialFrame: 0},
	{UITextTutorial: 0},
	{UIGold: 0},
	{UINoScrollZone: 0},
	{timeToBuild: 0},
	{QueueTimer: 0},
	{trainUnit: 0},
	{CPUTimer: 0},
	{GameTimer: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Projectile: 0},
	{CastEffect: 0},
	{ProjectileHit: 0},
	{Shadow: 0},
	{Lightning: 0},
	{ProjDestroyZone: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{AJAX: 0},
	{DictBuildTimes: 0},
	{Touch: 0},
	{DictPrices: 0},
	{AdvancedRandom: 0},
	{PlatformInfo: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{ArrBGM: 0},
	{TSBackground: 0},
	{TSTitle: 0},
	{posX: 0},
	{TSBorders: 0},
	{TitlescreenFull: 0},
	{startingX: 0},
	{startingY: 0},
	{finalX: 0},
	{finalY: 0},
	{order: 0},
	{TSUnit: 0},
	{TSVsSprite: 0},
	{TSVsSpriteTop: 0},
	{TSVignette: 0},
	{MMAudioButton: 0},
	{MMFrame: 0},
	{MMPlayButton: 0},
	{MMResetButton: 0},
	{MMCancelButton: 0},
	{MMConfirmButton: 0},
	{MMResetFrame: 0},
	{MMResetText: 0},
	{MMPressAnything: 0},
	{CreditsText: 0},
	{CreditsUnit: 0},
	{CreditsEnd: 0},
	{UIQueueFamily: 0},
	{Units: 0},
	{UnitsCollision: 0},
	{MMButtons: 0},
	{UIButtons: 0},
	{MAX_HEALTH: 0},
	{MAX_UNITS: 0},
	{AGES: 0},
	{LIGHTNING_DAMAGE: 0},
	{goldMultiplier: 0},
	{gameTime: 0},
	{gamePaused: 0},
	{tutorial: 0},
	{gameOver: 0},
	{inGameTransition: 0},
	{inQueue: 0},
	{playerAge: 0},
	{gold: 0},
	{playerHealth: 0},
	{turretSpots: 0},
	{CPUDifficulty: 0},
	{CPUEnergy: 0},
	{CPUEnergyPreFrenzy: 0},
	{CPUHealth: 0},
	{CPUAge: 0},
	{maxMaterial: 0},
	{playerMaterial: 0},
	{pointA: 0},
	{pointB: 0},
	{pointC: 0},
	{distAB: 0},
	{distCB: 0},
	{distAC: 0},
	{MAX_URGENCY_DIST: 0},
	{urgency: 0},
	{effectiveRange: 0},
	{baseTime: 0},
	{totalTime: 0},
	{turretNum: 0},
	{SCROLL_SPEED: 0},
	{dragStartX: 0},
	{turretCount: 0},
	{currentTurretTool: 0},
	{lastChar: 0},
	{type: 0},
	{item: 0},
	{multiplier: 0},
	{CPUTTag: 0},
	{unitUID: 0},
	{attackingCiv: 0},
	{attackedCiv: 0},
	{attacked: 0},
	{MELEE_ATTACK_RANGE: 0},
	{success: 0},
	{x: 0},
	{y: 0},
	{angleOfMotion: 0},
	{animation: 0},
	{mobileControls: 0},
	{titleScreenReady: 0},
	{playingTransition: 0},
	{audio: 0},
	{level: 0},
	{CREDITS_SPEED: 0},
	{BGM_VOLUME: 0},
	{BGM_LOW_VOLUME: 0},
	{SFX_VOLUME: 0},
	{BGMPlayed: 0},
	{SFXBlock: 0},
	{name: 0},
	{tag: 0},
	{volumeTweak: 0},
	{pitch: 0},
	{fadeOut: 0},
	{fadeIn: 0},
	{low: 0},
	{forceSilent: 0},
	{in: 0},
	{fadeTime: 0}
];

self.InstanceType = {
	BasePlayer: class extends self.ISpriteInstance {},
	BaseSprite: class extends self.ISpriteInstance {},
	TurretSpotsPlayer: class extends self.ISpriteInstance {},
	BaseCPU: class extends self.ISpriteInstance {},
	BaseSpotMarker: class extends self.ISpriteInstance {},
	Turret: class extends self.ISpriteInstance {},
	TurretSpotsCPU: class extends self.ISpriteInstance {},
	CPUSpawner: class extends self.ISpriteInstance {},
	PlayerSpawner: class extends self.ISpriteInstance {},
	BaseSpriteFront: class extends self.ISpriteInstance {},
	BaseBed: class extends self.ISpriteInstance {},
	TurretCPU: class extends self.ISpriteInstance {},
	Civ0Melee: class extends self.ISpriteInstance {},
	Civ0Ranged: class extends self.ISpriteInstance {},
	Civ0Super: class extends self.ISpriteInstance {},
	Civ1Melee: class extends self.ISpriteInstance {},
	Civ1Ranged: class extends self.ISpriteInstance {},
	Civ1Super: class extends self.ISpriteInstance {},
	UnitDeathAnim: class extends self.ISpriteInstance {},
	Civ0UnitTarget: class extends self.ISpriteInstance {},
	Civ1UnitTarget: class extends self.ISpriteInstance {},
	Parallax0: class extends self.ISpriteInstance {},
	Parallax1: class extends self.ISpriteInstance {},
	Foreground: class extends self.ISpriteInstance {},
	Sky: class extends self.ISpriteInstance {},
	UIIcon: class extends self.ISpriteInstance {},
	UITextDescription: class extends self.ISpriteFontInstance {},
	UIQueue: class extends self.ISpriteInstance {},
	UITextAge: class extends self.ISpriteFontInstance {},
	UIProgress: class extends self.ITiledBackgroundInstance {},
	UIProgressBackground: class extends self.ISpriteInstance {},
	UIMenuArea: class extends self.ITiledBackgroundInstance {},
	UIGameArea: class extends self.ITiledBackgroundInstance {},
	UIHealthBackground: class extends self.ISpriteInstance {},
	UIHealth: class extends self.ITiledBackgroundInstance {},
	UITextFunds: class extends self.ISpriteFontInstance {},
	UITextGold: class extends self.ISpriteFontInstance {},
	SpecialProgress: class extends self.ITiledBackgroundInstance {},
	UITextClock: class extends self.ISpriteFontInstance {},
	UIDecoration: class extends self.ISpriteInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	UIWinDefeat: class extends self.ISpriteInstance {},
	UIMenuText: class extends self.ISpriteFontInstance {},
	UICancelButton: class extends self.ISpriteInstance {},
	UIConfirmButton: class extends self.ISpriteInstance {},
	UIMenuFrame: class extends self.ISpriteInstance {},
	UIPauseButton: class extends self.ISpriteInstance {},
	UIToggleSoundButton: class extends self.ISpriteInstance {},
	UITutorialButton: class extends self.ISpriteInstance {},
	UITutorialFrame: class extends self.IWorldInstance {},
	UITextTutorial: class extends self.ISpriteFontInstance {},
	UIGold: class extends self.ISpriteInstance {},
	UINoScrollZone: class extends self.ITiledBackgroundInstance {},
	QueueTimer: class extends self.ISpriteInstance {},
	CPUTimer: class extends self.ISpriteInstance {},
	GameTimer: class extends self.ISpriteInstance {},
	Projectile: class extends self.ISpriteInstance {},
	CastEffect: class extends self.ISpriteInstance {},
	ProjectileHit: class extends self.ISpriteInstance {},
	Shadow: class extends self.ISpriteInstance {},
	Lightning: class extends self.ISpriteInstance {},
	ProjDestroyZone: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	DictBuildTimes: class extends self.IDictionaryInstance {},
	Touch: class extends self.IInstance {},
	DictPrices: class extends self.IDictionaryInstance {},
	AdvancedRandom: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	ArrBGM: class extends self.IArrayInstance {},
	TSBackground: class extends self.ISpriteInstance {},
	TSTitle: class extends self.ISpriteInstance {},
	TSBorders: class extends self.ISpriteInstance {},
	TitlescreenFull: class extends self.ISpriteInstance {},
	TSUnit: class extends self.ISpriteInstance {},
	TSVsSprite: class extends self.ISpriteInstance {},
	TSVsSpriteTop: class extends self.ISpriteInstance {},
	TSVignette: class extends self.ISpriteInstance {},
	MMAudioButton: class extends self.ISpriteInstance {},
	MMFrame: class extends self.ISpriteInstance {},
	MMPlayButton: class extends self.ISpriteInstance {},
	MMResetButton: class extends self.ISpriteInstance {},
	MMCancelButton: class extends self.ISpriteInstance {},
	MMConfirmButton: class extends self.ISpriteInstance {},
	MMResetFrame: class extends self.ISpriteInstance {},
	MMResetText: class extends self.ISpriteFontInstance {},
	MMPressAnything: class extends self.ISpriteFontInstance {},
	CreditsText: class extends self.ISpriteFontInstance {},
	CreditsUnit: class extends self.ISpriteInstance {},
	CreditsEnd: class extends self.ISpriteInstance {},
	UIQueueFamily: class extends self.ISpriteInstance {},
	Units: class extends self.ISpriteInstance {},
	UnitsCollision: class extends self.ISpriteInstance {},
	MMButtons: class extends self.ISpriteInstance {},
	UIButtons: class extends self.ISpriteInstance {}
}