const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Behaviors.Platform,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Rotate,
		C3.Plugins.NinePatch,
		C3.Behaviors.Sin,
		C3.Plugins.gamepad,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Platform.Exps.GravityAngle,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.System.Exps.random,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.right,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Tilemap.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.Touch.Cnds.CompareOrientation,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Platform.Acts.SetGravityAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Behaviors.MoveTo.Exps.MovingAngle,
		C3.Plugins.NinePatch.Exps.Angle,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.gamepad.Cnds.OnAnyButtonDown,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.TiledBg.Acts.SetEffectParam,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.LocalStorage.Cnds.IsProcessingSets,
		C3.Plugins.LocalStorage.Cnds.IsProcessingGets,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.PlatformInfo.Acts.RequestWakeLock,
		C3.Plugins.Touch.Acts.RequestPermission,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Particles.Acts.SetOpacity,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetY
	];
};
self.C3_JsPropNameTable = [
	{validForGAngle: 0},
	{NoLoss: 0},
	{invertFrog: 0},
	{FrogSpawn: 0},
	{patrolID: 0},
	{waypointID: 0},
	{Waypoint: 0},
	{dashID: 0},
	{DashDestination: 0},
	{FlyQueenWaypoint: 0},
	{FlyQueenSpawnpoint: 0},
	{Keyboard: 0},
	{PlatformInfo: 0},
	{Touch: 0},
	{Mouse: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{Background: 0},
	{flyID: 0},
	{smashed: 0},
	{FlyStand: 0},
	{canLose: 0},
	{Platform: 0},
	{Tween: 0},
	{Timer: 0},
	{Frog: 0},
	{Solid: 0},
	{Tilemap: 0},
	{FrogSprite: 0},
	{TextTutorial: 0},
	{Fireflies: 0},
	{TextNice: 0},
	{invertRot: 0},
	{Grass: 0},
	{nextWaypoint: 0},
	{MoveTo: 0},
	{FlyPatrol: 0},
	{enabledBy: 0},
	{FlyLocked: 0},
	{Dash: 0},
	{ShockwaveEffect: 0},
	{GravityInverter: 0},
	{Rotate: 0},
	{FlyParticles: 0},
	{Slash: 0},
	{Vine: 0},
	{fromID: 0},
	{toID: 0},
	{FlyLockedLink: 0},
	{FlyLockedLinkMask: 0},
	{FrogDashGhost: 0},
	{group: 0},
	{startingHeight: 0},
	{Barrier: 0},
	{SwitchBase: 0},
	{activeGroup: 0},
	{totalGroups: 0},
	{Switch: 0},
	{ButtonMainMenu: 0},
	{FlyQueen: 0},
	{TextTitle: 0},
	{TextTitleInteract: 0},
	{Sine: 0},
	{TitleFly: 0},
	{TitleFrame: 0},
	{TitleFrog: 0},
	{whichEye: 0},
	{centerX: 0},
	{centerY: 0},
	{TitleFrogEyeIris: 0},
	{TitleFrogEyeSclera: 0},
	{TitleFrogEyeExternal: 0},
	{FirefliesMenu: 0},
	{Gamepad: 0},
	{Fader: 0},
	{side: 0},
	{TransitionDoors: 0},
	{TransitionDoorsMenu: 0},
	{buttonEnabled: 0},
	{buttonID: 0},
	{leftPressID: 0},
	{rightPressID: 0},
	{downPressID: 0},
	{upPressID: 0},
	{LevelNumber: 0},
	{ButtonMenuLevel: 0},
	{ButtonMenuBGM: 0},
	{ButtonMenuSFX: 0},
	{MenuFrameAudio: 0},
	{MenuFrameReset: 0},
	{ButtonMenuReset: 0},
	{ButtonMenuBGMIcon: 0},
	{ButtonMenuResetIcon: 0},
	{ButtonMenuSFXIcon: 0},
	{MenuFrameResetSure: 0},
	{ButtonMenuResetSure: 0},
	{TextButtonMenuLevel: 0},
	{TextButtonMenuSure: 0},
	{ButtonMenuResetNotSure: 0},
	{ButtonMenuResetSureIcon: 0},
	{ButtonMenuResetNotSureIcon: 0},
	{atButtonID: 0},
	{ButtonSelector: 0},
	{lastCreditsBlock: 0},
	{CreditsFrame: 0},
	{CreditsFly: 0},
	{TextCredits: 0},
	{MenuButtons: 0},
	{Flies: 0},
	{amtFlies: 0},
	{menuTransition: 0},
	{endGameTransition: 0},
	{linkCount: 0},
	{nextLevel: 0},
	{canCallMenu: 0},
	{areYouSureMenu: 0},
	{mainMenu: 0},
	{currLevel: 0},
	{BGMPlaying: 0},
	{SFXPlaying: 0},
	{oldMouseX: 0},
	{oldMouseY: 0},
	{quickMenuMode: 0},
	{soundVolume: 0},
	{interval: 0},
	{result: 0},
	{i: 0},
	{text: 0},
	{creditsFadingOut: 0}
];

self.InstanceType = {
	NoLoss: class extends self.ITiledBackgroundInstance {},
	FrogSpawn: class extends self.ITiledBackgroundInstance {},
	Waypoint: class extends self.ISpriteInstance {},
	DashDestination: class extends self.ISpriteInstance {},
	FlyQueenWaypoint: class extends self.ISpriteInstance {},
	FlyQueenSpawnpoint: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Background: class extends self.ISpriteInstance {},
	FlyStand: class extends self.ISpriteInstance {},
	Frog: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	FrogSprite: class extends self.ISpriteInstance {},
	TextTutorial: class extends self.ITextInstance {},
	Fireflies: class extends self.IParticlesInstance {},
	TextNice: class extends self.ITextInstance {},
	Grass: class extends self.ISpriteInstance {},
	FlyPatrol: class extends self.ISpriteInstance {},
	FlyLocked: class extends self.ISpriteInstance {},
	Dash: class extends self.ISpriteInstance {},
	ShockwaveEffect: class extends self.ISpriteInstance {},
	GravityInverter: class extends self.ISpriteInstance {},
	FlyParticles: class extends self.ISpriteInstance {},
	Slash: class extends self.ISpriteInstance {},
	Vine: class extends self.I9PatchInstance {},
	FlyLockedLink: class extends self.ITiledBackgroundInstance {},
	FlyLockedLinkMask: class extends self.ISpriteInstance {},
	FrogDashGhost: class extends self.ISpriteInstance {},
	Barrier: class extends self.I9PatchInstance {},
	SwitchBase: class extends self.I9PatchInstance {},
	Switch: class extends self.ISpriteInstance {},
	ButtonMainMenu: class extends self.ISpriteInstance {},
	FlyQueen: class extends self.ISpriteInstance {},
	TextTitle: class extends self.ITextInstance {},
	TextTitleInteract: class extends self.ITextInstance {},
	TitleFly: class extends self.ISpriteInstance {},
	TitleFrame: class extends self.ISpriteInstance {},
	TitleFrog: class extends self.ISpriteInstance {},
	TitleFrogEyeIris: class extends self.ISpriteInstance {},
	TitleFrogEyeSclera: class extends self.ISpriteInstance {},
	TitleFrogEyeExternal: class extends self.ISpriteInstance {},
	FirefliesMenu: class extends self.IParticlesInstance {},
	Gamepad: class extends self.IInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	TransitionDoors: class extends self.ITiledBackgroundInstance {},
	TransitionDoorsMenu: class extends self.ITiledBackgroundInstance {},
	ButtonMenuLevel: class extends self.ISpriteInstance {},
	ButtonMenuBGM: class extends self.ISpriteInstance {},
	ButtonMenuSFX: class extends self.ISpriteInstance {},
	MenuFrameAudio: class extends self.ISpriteInstance {},
	MenuFrameReset: class extends self.ISpriteInstance {},
	ButtonMenuReset: class extends self.ISpriteInstance {},
	ButtonMenuBGMIcon: class extends self.ISpriteInstance {},
	ButtonMenuResetIcon: class extends self.ISpriteInstance {},
	ButtonMenuSFXIcon: class extends self.ISpriteInstance {},
	MenuFrameResetSure: class extends self.ISpriteInstance {},
	ButtonMenuResetSure: class extends self.ISpriteInstance {},
	TextButtonMenuLevel: class extends self.ITextInstance {},
	TextButtonMenuSure: class extends self.ITextInstance {},
	ButtonMenuResetNotSure: class extends self.ISpriteInstance {},
	ButtonMenuResetSureIcon: class extends self.ISpriteInstance {},
	ButtonMenuResetNotSureIcon: class extends self.ISpriteInstance {},
	ButtonSelector: class extends self.ISpriteInstance {},
	CreditsFrame: class extends self.ISpriteInstance {},
	CreditsFly: class extends self.ISpriteInstance {},
	TextCredits: class extends self.ITextInstance {},
	MenuButtons: class extends self.ISpriteInstance {},
	Flies: class extends self.ISpriteInstance {}
}